<?php
namespace app\home\controller;

use app\BaseController;
use mall\library\wechat\chat\WeChat;
use mall\utils\Tool;
use think\facade\Db;
use think\facade\Request;
use function GuzzleHttp\Psr7\str;

class Index {

    private function _index(){
        $arr = [
            [
                "name"=>"面部护肤",
                "children"=>[
                    [
                        "name"=>"美白",
                        "children"=>[
                            "面霜","乳液","啫喱/凝露"
                        ]
                    ],
                    [
                        "name"=>"防晒",
                        "children"=>[
                            "防晒霜/乳","晒后修复","防晒喷雾","防晒啫喱/露"
                        ]
                    ],
                    [
                        "name"=>"面膜",
                        "children"=>[
                            "粉末状","贴片式","水洗式","撕拉式","睡眠面膜","DIY面膜"
                        ]
                    ],
                    [
                        "name"=>"洁面",
                        "children"=>[
                            "洁面乳","洁面皂","洁面粉","洁面霜/膏","泡沫/摩丝","洁肤啫哩"
                        ]
                    ],
                    [
                        "name"=>"爽肤水",
                        "children"=>[
                            "爽肤水","紧肤水","柔肤水","洁肤水","喷雾","精华水"
                        ]
                    ],
                    [
                        "name"=>"精华",
                        "children"=>[
                            "敏感性","中性","干性","油性","混合性","任何肤质"
                        ]
                    ],
                    [
                        "name"=>"T区护理",
                        "children"=>[
                            "T区护理套装","吸油纸","鼻帖","鼻膜"
                        ]
                    ],
                    [
                        "name"=>"唇部",
                        "children"=>[
                            "润唇膏","润唇啫喱","润唇球"
                        ]
                    ]
                ]
            ],
            [
                "name"=>"彩妆",
                "children"=>[
                    [
                        "name"=>"隔离",
                        "children"=>[
                            "妆前乳","隔离霜"
                        ]
                    ],
                    [
                        "name"=>"遮瑕",
                        "children"=>[
                            "遮瑕膏/笔","遮瑕液","遮瑕粉","遮瑕盘"
                        ]
                    ],
                    [
                        "name"=>"气垫BB/BB霜",
                        "children"=>[
                            "BB霜","气垫BB"
                        ]
                    ],
                    [
                        "name"=>"粉底",
                        "children"=>[
                            "粉底液","粉底膏","粉底霜","修容棒"
                        ]
                    ],
                    [
                        "name"=>"腮红",
                        "children"=>[
                            "单色腮红","多色腮红","双色腮红"
                        ]
                    ],
                    [
                        "name"=>"口红",
                        "children"=>[
                            "口红","唇彩","唇蜜","唇釉","修护","修饰肤色","不沾杯","易上色"
                        ]
                    ],
                    [
                        "name"=>"睫毛膏",
                        "children"=>[
                            "单头睫毛膏","双头睫毛膏","两只组合型睫毛膏","睫毛底膏",
                            "睫毛雨衣","睫毛增长液"
                        ]
                    ],
                    [
                        "name"=>"眼影",
                        "children"=>[
                            "眼影棒/笔","单色眼影","眼影盘","液体眼影",
                            "眼影膏"
                        ]
                    ],
                    [
                        "name"=>"眼线",
                        "children"=>[
                            "眼线笔","眼线液","眼线膏/胶"
                        ]
                    ],
                    [
                        "name"=>"眉粉",
                        "children"=>[
                            "眉粉","染眉膏","眉笔","眉毛雨衣","眉胶","眉液"
                        ]
                    ],
                    [
                        "name"=>"散粉",
                        "children"=>[
                            "散粉","蜜粉","定妆水","定妆喷雾"
                        ]
                    ],
                    [
                        "name"=>"彩妆套装",
                        "children"=>[
                            "组合装","礼盒装","彩盘","限量/定制装"
                        ]
                    ]
                ]
            ],
            [
                "name"=>"男士护肤",
                "children"=>[
                    [
                        "name"=>"洁面",
                        "children"=>[
                            "洁面乳","洁面皂","洁面粉","洁面霜/膏","泡沫/摩丝","洁肤啫哩"
                        ]
                    ],
                    [
                        "name"=>"乳液",
                        "children"=>[
                            "面霜","乳液","啫喱/凝露"
                        ]
                    ],
                    [
                        "name"=>"面膜",
                        "children"=>[
                            "贴片式","水洗式","撕拉式","睡眠面膜","DIY面膜"
                        ]
                    ],
                    [
                        "name"=>"爽肤水",
                        "children"=>[
                            "爽肤水","紧肤水","柔肤水","洁肤水","喷雾","精华水"
                        ]
                    ],
                    [
                        "name"=>"剃须",
                        "children"=>[
                            "手动剃须刀","须后水/露","剃须套装","剃须刀头/刀片","剃须泡沫/啫喱"
                        ]
                    ],
                    [
                        "name"=>"男士防晒",
                        "children"=>[
                            "防晒霜/乳","晒后修护","防晒喷雾","防晒啫喱/露"
                        ]
                    ],
                    [
                        "name"=>"面部精华",
                        "children"=>[
                            "美白淡斑","细致毛孔","控油平衡","补水保湿","提拉紧致",
                            "修护","提亮肤色","舒缓镇静","抗衰","祛痘/抗痘"
                        ]
                    ]
                ]
            ],
            [
                "name"=>"洗发护发",
                "children"=>[
                    [
                        "name"=>"洗发水",
                        "children"=>[
                            "控油","去屑","防脱"
                        ]
                    ],
                    [
                        "name"=>"护发素",
                        "children"=>[
                            "滋养","柔顺","修护"
                        ]
                    ],
                    [
                        "name"=>"造型",
                        "children"=>[
                            "啫喱膏/水","发蜡/泥","弹力素"
                        ]
                    ],
                    [
                        "name"=>"染发假发",
                        "children"=>[
                            "染发","假发"
                        ]
                    ],
                    [
                        "name"=>"套装",
                        "children"=>[
                            "洗发套装","旅行套装"
                        ]
                    ],
                    [
                        "name"=>"美发工具",
                        "children"=>[
                            "梳子","美发剪","卷发工具","假发发箍","蒸发帽","围布","假发胶片",
                            "长嘴夹","喷雾瓶","压嘴","剪刀包","理发刷"
                        ]
                    ],
                    [
                        "name"=>"发膜",
                        "children"=>[
                            "滋养","修护","柔顺","亮泽","烫后护卷","强韧防断发"
                        ]
                    ]
                ]
            ],
            [
                "name"=>"口腔护理",
                "children"=>[
                    [
                        "name"=>"牙膏",
                        "children"=>[
                            "亮白","抗敏感","清新口气"
                        ]
                    ],
                    [
                        "name"=>"牙刷",
                        "children"=>[
                            "软毛","中毛","硬毛"
                        ]
                    ],
                    [
                        "name"=>"漱口水",
                        "children"=>[
                            "防蛀修护","美白牙齿"
                        ]
                    ],
                    [
                        "name"=>"牙线",
                        "children"=>[
                            "牙线","细滑线","扁线"
                        ]
                    ],
                    [
                        "name"=>"假牙清洁",
                        "children"=>[
                            "清洁片","稳固剂"
                        ]
                    ]
                ]
            ]
        ];

        foreach($arr as $value){
            if(Db::name("category")->where("title",$value['name'])->count()){
                break;
            }
            Db::name("category")->insert([
                "title"=>$value["name"],
                "module"=>"goods",
                "create_time"=>time()
            ]);
            $pid = Db::name("category")->getLastInsID();
            foreach($value["children"] as $val){
                Db::name("category")->insert([
                    "pid"=>$pid,
                    "title"=>$val["name"],
                    "module"=>"goods",
                    "create_time"=>time()
                ]);
                $cpid = Db::name("category")->getLastInsID();
                foreach($val["children"] as $item){
                    Db::name("category")->insert([
                        "pid"=>$cpid,
                        "title"=>$item,
                        "module"=>"goods",
                        "create_time"=>time()
                    ]);
                }
            }
        }
    }
}
